
title: Photo Gallery
email: 
description: >- # this means to ignore newlines until "baseurl:"
  Explorations in Film
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  mattarderne

exclude: [node_modules, Gemfile, Gemfile.lock, gulpfile.js, deploy.sh, README.md, index.md, .gitignore]

#--------------------------------------------
gallery:
  dir: photos
  title: "Photos"
  sort_field: "date"
  title_prefix: "" 
  symlink: false            # false: copy images into _site. true: create symbolic links (saves disk space)
  thumbnail_size:
    y: 450
    retina: 1.5
    
  # The following options are for individual galleries.
# gallery:
#   dir: photos
#   title: "Photos"
#   sort_field: "date"
#   thumbnail_size:
#     y: 450
#     retina: 1.5
#   galleries:
#     # b&w:
#     #   name: "b&w"
#     #   date: "2020/01/01"
#     #   best_image: 7-t.jpg
#     colour:
#       name: "colour"
#       date: "2020/01/01"
#       best_image: 12-t.jpg
